# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"
    filter_sets:
      cache: ~
      catalog_banner:
        quality: 75
        filters:
          thumbnail: { size: [1920, 500], mode: outbound }
      catalog_card_listing:
        quality: 75
        filters:
          thumbnail: { size: [260, 260], mode: outbound }
      picture_card_listing:
        quality: 75
        filters:
          thumbnail: { size: [260, 260], mode: outbound }
      picture:
        quality: 75
        filters:
          relative_resize:
            widen: 1050
      picture_square:
        quality: 75
        filters:
          thumbnail: { size: [260, 260], mode: outbound }
      picture_sm:
        quality: 75
        filters:
          relative_resize:
            widen: 400
      picture_md:
        quality: 75
        filters:
          relative_resize:
            widen: 800
      picture_lg:
        quality: 75
        filters:
          relative_resize:
            widen: 2048
      picture_vlg:
        quality: 75
        filters:
          relative_resize:
            widen: 2825