twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        twitter_username: archives_space
        twitter_numeric_id: 1325116350927429636

when@test:
    twig:
        strict_variables: true
