vich_uploader:
  db_driver: orm
  twig:      true
  storage: gaufrette
  mappings:
    catalog_picture:
      uri_prefix: "%env(AWS_BASE_URL)%/picture"
      upload_destination: picture_fs
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true
    catalog_cover:
      uri_prefix: "%env(AWS_BASE_URL)%/catalog"
      upload_destination: catalog_fs
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true